import * as fs from 'fs';
import * as path from 'path';
import { getFilesByStatuses, updateFileStatus, incrementRetryAndRequeue } from './db/files';
import { addLog } from './db/records';
import { ClaudeCodeRunner, CliError, getSessionLogPath } from './claude-cli';
import { Reconciler } from './reconciler';
import { ScriptRegistry } from './script-registry';
import { MatcherEvaluator } from './matcher-evaluator';
import { ScriptGenerator } from './script-generator';
import { ScriptVerifier } from './script-verifier';
import { executeScript } from './script-sandbox';
import { parseXmlInvoice } from './parsers/xml-invoice-parser';
import { extractMetadata } from './parsers/spreadsheet-metadata';
import { RelevanceFilter } from './filters/relevance-filter';
import { extractPdfText } from './filters/content-sniffer';
// Database accessed via vault handle
import { eventBus } from './event-bus';
import { FileStatus, LogLevel, VaultHandle, VaultFile, ExtractionResult, ClaudeModelConfig } from '../shared/types';
import {
  DEFAULT_BATCH_SIZE,
  DEFAULT_CLAUDE_MODELS,
  DEFAULT_MAX_RETRY_COUNT,
  MAX_BATCH_CONTEXT_BYTES,
  MIN_PDF_TEXT_CHARS,
  TEXT_TO_CONTEXT_RATIO,
  IMAGE_TO_CONTEXT_RATIO,
} from '../shared/constants';

const STRUCTURED_EXTENSIONS = new Set(['.xml', '.xlsx', '.csv']);
const SPREADSHEET_EXTENSIONS = new Set(['.xlsx', '.csv']);

export class ExtractionQueue {
  private pdfRunner: ClaudeCodeRunner;
  private scriptRunner: ClaudeCodeRunner;
  private reconciler: Reconciler;
  private scriptRegistry: ScriptRegistry;
  private matcherEvaluator: MatcherEvaluator;
  private scriptGenerator: ScriptGenerator;
  private scriptVerifier: ScriptVerifier;
  private vault: VaultHandle;
  private relevanceFilter: RelevanceFilter;
  private batchSize: number;
  private maxRetryCount: number;
  private processing = false;
  private pendingTrigger = false;

  constructor(vault: VaultHandle, relevanceFilter: RelevanceFilter, cliPath?: string, cliTimeout?: number, modelConfig?: ClaudeModelConfig) {
    this.vault = vault;
    this.relevanceFilter = relevanceFilter;
    const models = modelConfig ?? DEFAULT_CLAUDE_MODELS;
    this.pdfRunner = new ClaudeCodeRunner(cliPath, cliTimeout, models.pdfExtraction);
    this.scriptRunner = new ClaudeCodeRunner(cliPath, cliTimeout, models.scriptGeneration);
    this.reconciler = new Reconciler(vault.config.confidence_threshold);
    this.scriptRegistry = new ScriptRegistry(vault.db);
    this.matcherEvaluator = new MatcherEvaluator();
    this.scriptGenerator = new ScriptGenerator(this.scriptRunner);
    this.scriptVerifier = new ScriptVerifier(this.scriptRunner);
    this.batchSize = vault.config.extractionBatchSize ?? DEFAULT_BATCH_SIZE;
    this.maxRetryCount = vault.config.maxRetryCount ?? DEFAULT_MAX_RETRY_COUNT;
  }

  trigger(): void {
    if (this.processing) {
      this.pendingTrigger = true;
      return;
    }
    this.processQueue().catch(err => {
      console.error('[ExtractionQueue] Unhandled error:', err);
    });
  }

  private async processQueue(): Promise<void> {
    this.processing = true;

    try {
      while (true) {
        const allWork = getFilesByStatuses([FileStatus.Unfiltered, FileStatus.Pending]);
        if (allWork.length === 0) break;

        // Check if the next file is structured — process it alone so that each
        // structured file gets its own loop iteration and can reuse scripts
        // generated by earlier files in the same run.
        const nextFile = allWork[0];
        const nextExt = path.extname(nextFile.relative_path).toLowerCase();
        const isNextStructured = STRUCTURED_EXTENSIONS.has(nextExt);

        if (isNextStructured) {
          // Filter first if needed
          let file = nextFile;
          if (file.status === FileStatus.Unfiltered) {
            const outcome = await this.relevanceFilter.filterFile(file);
            if (outcome === 'skipped') continue;
            file = { ...file, status: FileStatus.Pending };
          }

          eventBus.emit('extraction:started', { fileIds: [file.id] });
          updateFileStatus(file.id, FileStatus.Processing);
          await this.processStructuredFile(file);
          continue;
        }

        // Next file is unstructured — collect a PDF/image batch from the front
        // of the queue (skip any structured files mixed in).
        const unstructuredCandidates: VaultFile[] = [];
        for (const file of allWork) {
          const ext = path.extname(file.relative_path).toLowerCase();
          if (STRUCTURED_EXTENSIONS.has(ext)) break; // stop at first structured file
          unstructuredCandidates.push(file);
          if (unstructuredCandidates.length >= this.batchSize) break;
        }

        // Run relevance filter on unfiltered files in this batch
        const toExtract: VaultFile[] = [];
        for (const file of unstructuredCandidates) {
          if (file.status === FileStatus.Unfiltered) {
            const outcome = await this.relevanceFilter.filterFile(file);
            if (outcome === 'skipped') continue;
            toExtract.push({ ...file, status: FileStatus.Pending });
          } else {
            toExtract.push(file);
          }
        }

        if (toExtract.length === 0) continue;

        // Slice by context budget before sending to Claude CLI
        const unstructuredBatch = await this.sliceByContextBudget(toExtract);
        if (unstructuredBatch.length === 0) break;

        const fileIds = unstructuredBatch.map(f => f.id);
        console.log(`[ExtractionQueue] Processing PDF/image batch of ${unstructuredBatch.length} files`);
        eventBus.emit('extraction:started', { fileIds });

        for (const file of unstructuredBatch) {
          updateFileStatus(file.id, FileStatus.Processing);
        }

        await this.processUnstructuredBatch(unstructuredBatch);
      }
    } finally {
      this.processing = false;
      if (this.pendingTrigger) {
        this.pendingTrigger = false;
        this.trigger();
      }
    }
  }

  private async sliceByContextBudget(files: VaultFile[]): Promise<VaultFile[]> {
    if (files.length === 0) return [];

    const selected: VaultFile[] = [];
    let estimatedBytes = 0;

    for (const file of files) {
      const fullPath = path.join(this.vault.rootPath, file.relative_path);
      const ext = path.extname(file.relative_path).toLowerCase();

      let fileEstimate: number;
      if (ext === '.pdf') {
        try {
          const text = await extractPdfText(fullPath);
          if (text.trim().length >= MIN_PDF_TEXT_CHARS) {
            fileEstimate = text.length * TEXT_TO_CONTEXT_RATIO;
          } else {
            // Scanned PDF — estimate from file size (base64 + context overhead)
            const stat = fs.statSync(fullPath);
            fileEstimate = stat.size * IMAGE_TO_CONTEXT_RATIO;
          }
        } catch {
          const stat = fs.statSync(fullPath);
          fileEstimate = stat.size * IMAGE_TO_CONTEXT_RATIO;
        }
      } else {
        // Non-PDF unstructured (images) — estimate from file size
        const stat = fs.statSync(fullPath);
        fileEstimate = stat.size * IMAGE_TO_CONTEXT_RATIO;
      }

      // Always include at least one file even if it exceeds the budget alone
      if (selected.length === 0 || estimatedBytes + fileEstimate <= MAX_BATCH_CONTEXT_BYTES) {
        selected.push(file);
        estimatedBytes += fileEstimate;
      } else {
        break;
      }
    }

    console.log(`[ExtractionQueue] Context budget: ~${(estimatedBytes / 1024 / 1024).toFixed(1)}MB for ${selected.length}/${files.length} unstructured files`);
    return selected;
  }

  private async processStructuredFile(file: VaultFile): Promise<void> {
    const structT0 = performance.now();
    const fullPath = path.join(this.vault.rootPath, file.relative_path);
    const ext = path.extname(file.relative_path).toLowerCase();
    console.log(`[ExtractionQueue] processStructuredFile: starting ${file.relative_path}`);

    try {
      // 1. Try built-in parsers first (XML e-invoices)
      if (ext === '.xml') {
        try {
          const fileResult = parseXmlInvoice(fullPath, file.relative_path);
          const extraction: ExtractionResult = { results: [fileResult] };
          this.reconciler.reconcileResults(extraction, 'xml-parser');
          console.log(`[ExtractionQueue] XML parsed directly: ${file.relative_path}`);
          return;
        } catch {
          console.log(`[ExtractionQueue] Built-in XML parser failed for ${file.relative_path}, trying cached scripts`);
        }
      }

      // 2. Try cached scripts via matcher evaluator
      const allScripts = this.scriptRegistry.getAllScripts();
      if (allScripts.length > 0) {
        const matchedScript = this.matcherEvaluator.findMatchingScript(fullPath, allScripts, this.vault.dotPath);
        if (matchedScript) {
          const scriptFullPath = path.join(this.vault.dotPath, matchedScript.script_path);
          const scriptExecT0 = performance.now();
          const result = await executeScript(scriptFullPath, fullPath);
          console.log(`[ExtractionQueue] executeScript took ${(performance.now() - scriptExecT0).toFixed(0)}ms for ${file.relative_path} (${result.records?.length ?? 0} records)`);
          result.relative_path = file.relative_path;
          this.scriptRegistry.recordUsage(matchedScript.id, file.id);
          const reconcileT0 = performance.now();
          this.reconciler.reconcileResults({ results: [result] }, `script:${matchedScript.name}`);
          console.log(`[ExtractionQueue] reconcileResults took ${(performance.now() - reconcileT0).toFixed(0)}ms for ${file.relative_path}`);
          console.log(`[ExtractionQueue] Processed with cached script "${matchedScript.name}": ${file.relative_path}`);
          return;
        }

      }

      // 3. For spreadsheets, use metadata-driven iterative script generation
      console.log(`[ExtractionQueue] No cached script matched, generating via metadata pipeline: ${file.relative_path}`);
      await this.processSpreadsheetWithMetadata(file, fullPath);
      console.log(`[ExtractionQueue] processStructuredFile: finished ${file.relative_path} in ${(performance.now() - structT0).toFixed(0)}ms`);
    } catch (err) {
      console.error(`[ExtractionQueue] Error processing structured file ${file.relative_path}:`, err);
      this.handleFileError(file, `Structured file error: ${file.relative_path}: ${(err as Error).message}`);
    }
  }

  private async processSpreadsheetWithMetadata(file: VaultFile, fullPath: string): Promise<void> {
    // 1. Extract metadata (pure local code, no AI)
    const metadata = extractMetadata(fullPath);
    console.log(`[ExtractionQueue] Extracted metadata: ${metadata.sheets.length} sheets, ${metadata.totalRows} total rows`);

    // 2. Generate initial parser script via AI
    const generated = await this.scriptGenerator.generateParser(metadata, this.vault.dotPath);
    console.log(`[ExtractionQueue] Generated parser: ${generated.name}`);

    // 3. Iterative verify-and-refine loop — Claude judges each iteration
    const verification = await this.scriptVerifier.verifyAndRefine(
      generated.parserPath, fullPath, metadata, this.vault.rootPath,
    );

    if (!verification.success) {
      throw new Error(`Script verification failed: ${verification.error}`);
    }

    // 4. Generate matcher script (for reuse with similar files)
    let matcherPath: string;
    try {
      const matcher = await this.scriptGenerator.generateMatcher(metadata, this.vault.dotPath, generated.name);
      matcherPath = matcher.matcherPath;
    } catch (err) {
      // Matcher generation failure is non-critical — parser still works
      console.warn(`[ExtractionQueue] Matcher generation failed (non-critical): ${(err as Error).message}`);
      matcherPath = '';
    }

    // 5. Register the script for reuse
    if (matcherPath) {
      const script = this.scriptRegistry.registerScript({
        name: generated.name,
        docType: generated.docType,
        scriptPath: path.relative(this.vault.dotPath, generated.parserPath),
        matcherPath: path.relative(this.vault.dotPath, matcherPath),
        description: `Auto-generated parser for ${metadata.fileName}`,
      });
      this.scriptRegistry.recordUsage(script.id, file.id);
    }

    // 6. Reconcile the verified output
    // Fix relative_path — parser scripts receive absolute path via process.argv[2],
    // but reconciler looks up files by relative path in the DB.
    verification.output!.relative_path = file.relative_path;
    this.reconciler.reconcileResults(
      { results: [verification.output!] },
      `script:${generated.name}`,
    );
    console.log(`[ExtractionQueue] Spreadsheet processed and reconciled: ${file.relative_path}`);
  }

  private async processUnstructuredBatch(files: VaultFile[]): Promise<void> {
    // Guard: reject spreadsheet files — Claude CLI cannot read binary xlsx/csv
    const processable: VaultFile[] = [];
    for (const file of files) {
      const ext = path.extname(file.relative_path).toLowerCase();
      if (SPREADSHEET_EXTENSIONS.has(ext)) {
        console.error(`[ExtractionQueue] Cannot send ${ext} to Claude CLI: ${file.relative_path}`);
        updateFileStatus(file.id, FileStatus.Error);
        addLog(null, LogLevel.Error, `Spreadsheet files cannot be processed by Claude CLI: ${file.relative_path}`, undefined, file.id);
        eventBus.emit('extraction:error', {
          fileId: file.id,
          error: `Spreadsheet files (${ext}) require the metadata pipeline, not Claude CLI`,
        });
      } else {
        processable.push(file);
      }
    }
    if (processable.length === 0) return;

    const filePaths = processable.map(f => path.join(this.vault.rootPath, f.relative_path));

    try {
      const systemPromptPath = path.join(this.vault.dotPath, 'instructions', 'extraction-prompt.md');
      const { result, sessionLog } = await this.pdfRunner.processFiles(filePaths, this.vault.rootPath, systemPromptPath);

      // Reconcile results
      this.reconciler.reconcileResults(result, sessionLog);

      // Handle files that weren't included in results (CLI may have skipped them)
      for (const file of processable) {
        const hasResult = result.results.some(r => r.relative_path === file.relative_path);
        if (!hasResult) {
          this.handleFileError(file, `No extraction result returned for ${file.relative_path}`);
        }
      }
    } catch (err) {
      console.error('[ExtractionQueue] Batch processing error:', err);
      const isCliErr = err instanceof CliError;
      const sessionLogPath = (isCliErr && err.sessionId)
        ? getSessionLogPath(this.vault.rootPath, err.sessionId)
        : null;
      const detail = JSON.stringify({
        exitCode: isCliErr ? err.exitCode : null,
        stderr: isCliErr ? err.stderr : null,
        partialStdout: isCliErr ? err.partialStdout : null,
        sessionLogPath,
      });
      for (const file of processable) {
        this.handleFileError(file, `Batch error for ${file.relative_path}: ${(err as Error).message}`, detail);
      }
    }
  }

  private handleFileError(file: VaultFile, errorMessage: string, logDetail?: string): void {
    if (file.retry_count < this.maxRetryCount) {
      incrementRetryAndRequeue(file.id);
      console.log(`[ExtractionQueue] Retrying file (attempt ${file.retry_count + 1}/${this.maxRetryCount}): ${file.relative_path}`);
      addLog(null, LogLevel.Warn, `Retrying file (attempt ${file.retry_count + 1}/${this.maxRetryCount}): ${file.relative_path}`, logDetail, file.id);
    } else {
      updateFileStatus(file.id, FileStatus.Error);
      addLog(null, LogLevel.Error, errorMessage, logDetail, file.id);
      eventBus.emit('extraction:error', {
        fileId: file.id,
        error: errorMessage,
      });
    }
  }

  isProcessing(): boolean {
    return this.processing;
  }
}
