import * as fs from 'fs';
import * as path from 'path';
import { getFilesByStatuses, updateFileStatus, incrementRetryAndRequeue } from './db/files';
import { addLog } from './db/records';
import { ClaudeCodeRunner, CliError, getSessionLogPath } from './claude-cli';
import { processFiles as processFilesWithCLI } from './pdf-extractor';
import { Reconciler } from './reconciler';
import { ScriptRegistry } from './script-registry';
import { MatcherEvaluator } from './matcher-evaluator';
import { ScriptGenerator } from './script-generator';
import { ScriptVerifier } from './script-verifier';
import { executeScript } from './script-sandbox';
import { parseXmlInvoice } from './parsers/xml-invoice-parser';
import { extractMetadata } from './parsers/spreadsheet-metadata';
import { RelevanceFilter } from './filters/relevance-filter';
import { extractPdfWithLiteParse } from './liteparse-extractor';
import { validateScriptOutput } from './validators/output-validator';
// Database accessed via vault handle
import { eventBus } from './event-bus';
import { log, LogModule } from './logger';
import { FileStatus, LogLevel, VaultHandle, VaultFile, ClaudeModelConfig } from '../shared/types';
import {
  DEFAULT_BATCH_SIZE,
  DEFAULT_CLAUDE_MODELS,
  DEFAULT_MAX_RETRY_COUNT,
  MAX_BATCH_CONTEXT_BYTES,
  TEXT_TO_CONTEXT_RATIO,
  IMAGE_TO_CONTEXT_RATIO,
} from '../shared/constants';

const STRUCTURED_EXTENSIONS = new Set(['.xml', '.xlsx', '.csv']);
const SPREADSHEET_EXTENSIONS = new Set(['.xlsx', '.csv']);

export class ExtractionQueue {
  private pdfRunner: ClaudeCodeRunner;
  private scriptRunner: ClaudeCodeRunner;
  private reconciler: Reconciler;
  private scriptRegistry: ScriptRegistry;
  private matcherEvaluator: MatcherEvaluator;
  private scriptGenerator: ScriptGenerator;
  private scriptVerifier: ScriptVerifier;
  private vault: VaultHandle;
  private relevanceFilter: RelevanceFilter;
  private batchSize: number;
  private maxRetryCount: number;
  private processing = false;
  private pendingTrigger = false;

  constructor(vault: VaultHandle, relevanceFilter: RelevanceFilter, cliPath?: string, cliTimeout?: number, modelConfig?: ClaudeModelConfig) {
    this.vault = vault;
    this.relevanceFilter = relevanceFilter;
    const models = modelConfig ?? DEFAULT_CLAUDE_MODELS;
    this.pdfRunner = new ClaudeCodeRunner(cliPath, cliTimeout, models.pdfExtraction, 'low');
    this.scriptRunner = new ClaudeCodeRunner(cliPath, cliTimeout, models.scriptGeneration, 'high');
    const matcherRunner = new ClaudeCodeRunner(cliPath, cliTimeout, models.scriptGeneration, 'low');
    this.reconciler = new Reconciler(vault.config.confidence_threshold);
    this.scriptRegistry = new ScriptRegistry(vault.db);
    this.matcherEvaluator = new MatcherEvaluator();
    this.scriptGenerator = new ScriptGenerator(this.scriptRunner, matcherRunner);
    this.scriptVerifier = new ScriptVerifier(this.scriptRunner);
    this.batchSize = vault.config.extractionBatchSize ?? DEFAULT_BATCH_SIZE;
    this.maxRetryCount = vault.config.maxRetryCount ?? DEFAULT_MAX_RETRY_COUNT;
  }

  trigger(): void {
    if (this.processing) {
      this.pendingTrigger = true;
      return;
    }
    this.processQueue().catch(err => {
      log.error(LogModule.ExtractionQueue, 'Unhandled error:', err);
    });
  }

  async reanalyzeFile(file: VaultFile, hint: string): Promise<void> {
    const fullPath = path.join(this.vault.rootPath, file.relative_path);
    const ext = path.extname(file.relative_path).toLowerCase();

    if (!SPREADSHEET_EXTENSIONS.has(ext)) {
      throw new Error(`Re-analyze is only supported for spreadsheet files, got ${ext}`);
    }

    log.info(LogModule.ExtractionQueue, `Re-analyzing ${file.relative_path} with user hint`);
    eventBus.emit('extraction:started', { fileIds: [file.id] });
    updateFileStatus(file.id, FileStatus.Processing);

    try {
      await this.processSpreadsheetWithMetadata(file, fullPath, hint);
    } catch (err) {
      log.error(LogModule.ExtractionQueue, `Re-analyze error for ${file.relative_path}:`, err);
      this.handleFileError(file, `Re-analyze error: ${file.relative_path}: ${(err as Error).message}`);
    }
  }

  private async processQueue(): Promise<void> {
    this.processing = true;

    try {
      while (true) {
        const allWork = getFilesByStatuses([FileStatus.Unfiltered, FileStatus.Pending]);
        if (allWork.length === 0) break;

        // Check if the next file is structured — process it alone so that each
        // structured file gets its own loop iteration and can reuse scripts
        // generated by earlier files in the same run.
        const nextFile = allWork[0];
        const nextExt = path.extname(nextFile.relative_path).toLowerCase();
        const isNextStructured = STRUCTURED_EXTENSIONS.has(nextExt);

        if (isNextStructured) {
          // Filter first if needed
          let file = nextFile;
          if (file.status === FileStatus.Unfiltered) {
            const outcome = await this.relevanceFilter.filterFile(file);
            if (outcome === 'skipped') continue;
            file = { ...file, status: FileStatus.Pending };
          }

          eventBus.emit('extraction:started', { fileIds: [file.id] });
          updateFileStatus(file.id, FileStatus.Processing);
          await this.processStructuredFile(file);
          continue;
        }

        // Next file is unstructured — collect a PDF/image batch from the front
        // of the queue (skip any structured files mixed in).
        const unstructuredCandidates: VaultFile[] = [];
        for (const file of allWork) {
          const ext = path.extname(file.relative_path).toLowerCase();
          if (STRUCTURED_EXTENSIONS.has(ext)) break; // stop at first structured file
          unstructuredCandidates.push(file);
          if (unstructuredCandidates.length >= this.batchSize) break;
        }

        // Run relevance filter on unfiltered files in this batch
        const toExtract: VaultFile[] = [];
        for (const file of unstructuredCandidates) {
          if (file.status === FileStatus.Unfiltered) {
            const outcome = await this.relevanceFilter.filterFile(file);
            if (outcome === 'skipped') continue;
            toExtract.push({ ...file, status: FileStatus.Pending });
          } else {
            toExtract.push(file);
          }
        }

        if (toExtract.length === 0) continue;

        // Slice by context budget before sending to Claude CLI
        const unstructuredBatch = await this.sliceByContextBudget(toExtract);
        if (unstructuredBatch.length === 0) break;

        const fileIds = unstructuredBatch.map(f => f.id);
        log.info(LogModule.ExtractionQueue, `Processing PDF/image batch of ${unstructuredBatch.length} files`);
        eventBus.emit('extraction:started', { fileIds });

        for (const file of unstructuredBatch) {
          updateFileStatus(file.id, FileStatus.Processing);
        }

        await this.processUnstructuredBatch(unstructuredBatch);
      }
    } finally {
      this.processing = false;
      if (this.pendingTrigger) {
        this.pendingTrigger = false;
        this.trigger();
      }
    }
  }

  private async sliceByContextBudget(files: VaultFile[]): Promise<VaultFile[]> {
    if (files.length === 0) return [];

    const selected: VaultFile[] = [];
    let estimatedBytes = 0;

    for (const file of files) {
      const fullPath = path.join(this.vault.rootPath, file.relative_path);
      const ext = path.extname(file.relative_path).toLowerCase();

      let fileEstimate: number;
      if (ext === '.pdf') {
        try {
          // LiteParse always produces text (native or OCR) — estimate from text length
          const lpResult = await extractPdfWithLiteParse(fullPath);
          fileEstimate = lpResult.text.length * TEXT_TO_CONTEXT_RATIO;
        } catch {
          const stat = fs.statSync(fullPath);
          fileEstimate = stat.size * TEXT_TO_CONTEXT_RATIO;
        }
      } else {
        // Non-PDF unstructured (images) — estimate from file size
        const stat = fs.statSync(fullPath);
        fileEstimate = stat.size * IMAGE_TO_CONTEXT_RATIO;
      }

      // Always include at least one file even if it exceeds the budget alone
      if (selected.length === 0 || estimatedBytes + fileEstimate <= MAX_BATCH_CONTEXT_BYTES) {
        selected.push(file);
        estimatedBytes += fileEstimate;
      } else {
        break;
      }
    }

    log.info(LogModule.ExtractionQueue, `Context budget: ~${(estimatedBytes / 1024 / 1024).toFixed(1)}MB for ${selected.length}/${files.length} unstructured files`);
    return selected;
  }

  private async processStructuredFile(file: VaultFile): Promise<void> {
    const structT0 = performance.now();
    const fullPath = path.join(this.vault.rootPath, file.relative_path);
    const ext = path.extname(file.relative_path).toLowerCase();
    log.info(LogModule.ExtractionQueue, `processStructuredFile: starting ${file.relative_path}`);

    try {
      // 1. Try built-in parsers first (XML e-invoices)
      if (ext === '.xml') {
        try {
          const fileResult = parseXmlInvoice(fullPath, file.relative_path);
          fileResult.file_id = file.id;
          this.reconciler.reconcileResults({ results: [fileResult] }, 'xml-parser');
          log.info(LogModule.ExtractionQueue, `XML parsed directly: ${file.relative_path}`);
          return;
        } catch {
          log.info(LogModule.ExtractionQueue, `Built-in XML parser failed for ${file.relative_path}, trying cached scripts`);
        }
      }

      // 2. Try cached scripts via matcher evaluator
      const allScripts = this.scriptRegistry.getAllScripts();
      log.info(LogModule.ExtractionQueue, `Step 2: checking ${allScripts.length} cached script(s) for ${file.relative_path}`);
      if (allScripts.length > 0) {
        const matchedScript = this.matcherEvaluator.findMatchingScript(fullPath, allScripts, this.vault.dotPath);
        if (matchedScript) {
          log.info(LogModule.ExtractionQueue, `Matched script "${matchedScript.name}" (${matchedScript.script_path}) — executing against ${file.relative_path}`);
          const scriptFullPath = path.join(this.vault.dotPath, matchedScript.script_path);
          const scriptExecT0 = performance.now();
          let result;
          try {
            result = await executeScript(scriptFullPath, fullPath);
          } catch (execErr) {
            log.warn(LogModule.ExtractionQueue, `Cached script "${matchedScript.name}" CRASHED for ${file.relative_path}: ${(execErr as Error).message}. Falling through to new script generation.`);
            result = null;
          }

          if (result) {
            const execMs = (performance.now() - scriptExecT0).toFixed(0);
            const recordCount = result.records?.length ?? 0;
            const parsingErrorCount = result._parsing_errors?.length ?? 0;
            log.info(LogModule.ExtractionQueue, `executeScript completed in ${execMs}ms — ${recordCount} records, ${parsingErrorCount} parsing errors reported`);

            if (parsingErrorCount > 0) {
              const errorSample = result._parsing_errors!.slice(0, 5).map(
                e => `  row ${e.row}: ${e.field} = ${JSON.stringify(e.rawValue)} (${e.error})`
              );
              log.info(LogModule.ExtractionQueue, `Parsing errors sample:\n${errorSample.join('\n')}${parsingErrorCount > 5 ? `\n  ... and ${parsingErrorCount - 5} more` : ''}`);
            }

            result.relative_path = file.relative_path;

            const validation = validateScriptOutput(result, { scriptDocType: matchedScript.doc_type });
            log.info(LogModule.ExtractionQueue, `Output validation: valid=${validation.valid}${validation.warnings.length > 0 ? `, warnings: [${validation.warnings.join('; ')}]` : ''}`);

            if (validation.valid) {
              this.scriptRegistry.recordUsage(matchedScript.id, file.id);
              const reconcileT0 = performance.now();
              result.file_id = file.id;
              this.reconciler.reconcileResults({ results: [result] }, `script:${matchedScript.name}`);
              log.info(LogModule.ExtractionQueue, `reconcileResults took ${(performance.now() - reconcileT0).toFixed(0)}ms for ${file.relative_path}`);
              log.info(LogModule.ExtractionQueue, `SUCCESS: ${file.relative_path} processed with cached script "${matchedScript.name}"`);
              return;
            }

            log.warn(LogModule.ExtractionQueue, `REJECTED cached script "${matchedScript.name}" for ${file.relative_path} — generating new script`);
          }
        } else {
          log.info(LogModule.ExtractionQueue, `No cached script matched ${file.relative_path}`);
        }
      }

      // 3. For spreadsheets, use metadata-driven iterative script generation
      log.info(LogModule.ExtractionQueue, `No cached script matched, generating via metadata pipeline: ${file.relative_path}`);
      await this.processSpreadsheetWithMetadata(file, fullPath);
      log.info(LogModule.ExtractionQueue, `processStructuredFile: finished ${file.relative_path} in ${(performance.now() - structT0).toFixed(0)}ms`);
    } catch (err) {
      log.error(LogModule.ExtractionQueue, `Error processing structured file ${file.relative_path}:`, err);
      this.handleFileError(file, `Structured file error: ${file.relative_path}: ${(err as Error).message}`);
    }
  }

  private async processSpreadsheetWithMetadata(file: VaultFile, fullPath: string, userHint?: string): Promise<void> {
    log.info(LogModule.ExtractionQueue, `── New script generation pipeline for ${file.relative_path} ──`);
    // 1. Extract metadata (pure local code, no AI)
    const metadata = extractMetadata(fullPath);
    const sheetSummary = metadata.sheets.map(s => `"${s.name}" (${s.rowCount} rows, ${s.colCount} cols, headers: [${s.headers.slice(0, 8).join(', ')}${s.headers.length > 8 ? `, +${s.headers.length - 8} more` : ''}])`).join(', ');
    log.info(LogModule.ExtractionQueue, `Metadata: ${metadata.sheets.length} sheet(s) — ${sheetSummary}`);

    // 2. Generate initial parser script via AI
    const generated = await this.scriptGenerator.generateParser(metadata, this.vault.dotPath, userHint);
    log.info(LogModule.ExtractionQueue, `Generated parser: ${generated.name}`);

    // 3. Iterative verify-and-refine loop — Claude judges each iteration
    const verification = await this.scriptVerifier.verifyAndRefine(
      generated.parserPath, fullPath, metadata, this.vault.rootPath,
    );

    if (!verification.success) {
      throw new Error(`Script verification failed: ${verification.error}`);
    }

    // 4. Generate matcher script (for reuse with similar files)
    let matcherPath: string;
    try {
      const matcher = await this.scriptGenerator.generateMatcher(metadata, this.vault.dotPath, generated.name);
      matcherPath = matcher.matcherPath;
    } catch (err) {
      // Matcher generation failure is non-critical — parser still works
      log.warn(LogModule.ExtractionQueue, `Matcher generation failed (non-critical): ${(err as Error).message}`);
      matcherPath = '';
    }

    // 5. Register the script for reuse
    if (matcherPath) {
      const script = this.scriptRegistry.registerScript({
        name: generated.name,
        docType: generated.docType,
        scriptPath: path.relative(this.vault.dotPath, generated.parserPath),
        matcherPath: path.relative(this.vault.dotPath, matcherPath),
        description: `Auto-generated parser for ${metadata.fileName}`,
        userHint: userHint,
      });
      this.scriptRegistry.recordUsage(script.id, file.id);
    }

    // 6. Reconcile the verified output
    // Fix relative_path — parser scripts receive absolute path via process.argv[2],
    // but reconciler looks up files by relative path in the DB.
    verification.output!.relative_path = file.relative_path;
    verification.output!.file_id = file.id;
    this.reconciler.reconcileResults(
      { results: [verification.output!] },
      `script:${generated.name}`,
    );
    log.info(LogModule.ExtractionQueue, `Spreadsheet processed and reconciled: ${file.relative_path}`);
  }

  private async processUnstructuredBatch(files: VaultFile[]): Promise<void> {
    // Guard: reject spreadsheet files — Claude CLI cannot read binary xlsx/csv
    const processable: VaultFile[] = [];
    for (const file of files) {
      const ext = path.extname(file.relative_path).toLowerCase();
      if (SPREADSHEET_EXTENSIONS.has(ext)) {
        log.error(LogModule.ExtractionQueue, `Cannot send ${ext} to Claude CLI: ${file.relative_path}`);
        updateFileStatus(file.id, FileStatus.Error);
        addLog(null, LogLevel.Error, `Spreadsheet files cannot be processed by Claude CLI: ${file.relative_path}`, undefined, file.id);
        eventBus.emit('extraction:error', {
          fileId: file.id,
          error: `Spreadsheet files (${ext}) require the metadata pipeline, not Claude CLI`,
        });
      } else {
        processable.push(file);
      }
    }
    if (processable.length === 0) return;

    const filePaths = processable.map(f => path.join(this.vault.rootPath, f.relative_path));

    try {
      const systemPromptPath = path.join(this.vault.dotPath, 'instructions', 'extraction-prompt.md');
      const { result, sessionLog } = await processFilesWithCLI(this.pdfRunner, filePaths, this.vault.rootPath, systemPromptPath);

      // Stamp file_id on each result to avoid Unicode normalization mismatch
      // (macOS stores NFD paths in DB, but Claude CLI returns NFC paths in JSON)
      const nfcPathToFile = new Map(processable.map(f => [f.relative_path.normalize('NFC'), f]));
      for (const fileResult of result.results) {
        const matched = nfcPathToFile.get(fileResult.relative_path.normalize('NFC'));
        if (matched) fileResult.file_id = matched.id;
      }
      this.reconciler.reconcileResults(result, sessionLog);

      // Handle files that weren't included in results (CLI may have skipped them)
      for (const file of processable) {
        const hasResult = result.results.some(r => r.file_id === file.id);
        if (!hasResult) {
          this.handleFileError(file, `No extraction result returned for ${file.relative_path}`);
        }
      }
    } catch (err) {
      log.error(LogModule.ExtractionQueue, 'Batch processing error:', err);
      const isCliErr = err instanceof CliError;
      const sessionLogPath = (isCliErr && err.sessionId)
        ? getSessionLogPath(this.vault.rootPath, err.sessionId)
        : null;
      const detail = JSON.stringify({
        exitCode: isCliErr ? err.exitCode : null,
        stderr: isCliErr ? err.stderr : null,
        partialStdout: isCliErr ? err.partialStdout : null,
        sessionLogPath,
      });
      for (const file of processable) {
        this.handleFileError(file, `Batch error for ${file.relative_path}: ${(err as Error).message}`, detail);
      }
    }
  }

  private handleFileError(file: VaultFile, errorMessage: string, logDetail?: string): void {
    if (file.retry_count < this.maxRetryCount) {
      incrementRetryAndRequeue(file.id);
      log.info(LogModule.ExtractionQueue, `Retrying file (attempt ${file.retry_count + 1}/${this.maxRetryCount}): ${file.relative_path}`);
      addLog(null, LogLevel.Warn, `Retrying file (attempt ${file.retry_count + 1}/${this.maxRetryCount}): ${file.relative_path}`, logDetail, file.id);
    } else {
      updateFileStatus(file.id, FileStatus.Error);
      addLog(null, LogLevel.Error, errorMessage, logDetail, file.id);
      eventBus.emit('extraction:error', {
        fileId: file.id,
        error: errorMessage,
      });
    }
  }

  isProcessing(): boolean {
    return this.processing;
  }
}
