#!/usr/bin/env sh

if [ -f "$(dirname -- "$0")/_/.env" ]; then
  . "$(dirname -- "$0")/_/.env"
  export PATH="${PATH}:${EXT_PATH}"
fi

echo "Running checks: tsc, lint, test (in parallel)..."

pnpm tsc & tsc_pid=$!
pnpm lint & lint_pid=$!
pnpm test & test_pid=$!

for pid in $tsc_pid $lint_pid $test_pid; do
  wait $pid || exit 1
done
