#!/usr/bin/env sh

if [ -f "$(dirname -- "$0")/_/.env" ]; then
  . "$(dirname -- "$0")/_/.env"
  export PATH="${PATH}:${EXT_PATH}"
fi

echo "Running checks: tsc, lint, test (in parallel)..."

pnpm tsc &
pnpm lint &
pnpm test &

wait
echo "OK!"

# pnpm tsc &
# tsc_pid=$!

# pnpm lint &
# lint_pid=$!

# pnpm test &
# test_pid=$!

# status=0

# wait_for() {
#   pid=$1
#   name=$2

#   if ! wait "$pid"; then
#     echo "$name failed"
#     status=1
#   fi
# }

# wait_for "$tsc_pid" "tsc"
# wait_for "$lint_pid" "lint"
# wait_for "$test_pid" "test"

# exit "$status"
