#!/usr/bin/env sh

if [ -f "$(dirname -- "$0")/_/.env" ]; then
  . "$(dirname -- "$0")/_/.env"
  export PATH="${PATH}:${EXT_PATH}"
fi

# echo "Lint check"
# pnpm lint

# echo "Tsc check"
# pnpm tsc

echo "Test check"
pnpm test
